### PR TITLE
Invalid `domain` although it should be valid

### LINKED ISSUE #33: Invalid `domain` although it should be valid
Your regex doesn't handle longer domain names like AWS can give.

https://github.com/bytesbay/web3-token/blob/d33a0b52e8d79014980045188bed0f1d47e49b17/src/lib/sign/sign.js#L5

For instance, the domain `example.s3-website.us-east-1.amazonaws.com` isn't considered valid although this is something which is perfectly possible in the real world.

I suggest you should use a package for this validation instead: https://www.npmjs.com/package/is-valid-domain for instance.

### PR DESCRIPTION
**Pull request by Drarig29**
Fixes #33

### CODE REVIEW

**Comment by bytesbay** [comment]
Great! You want me to publish after that request ?

**Comment by Drarig29** [comment]
Not still ah ah, I have two other PRs coming up :grin:

**Comment by Drarig29** [comment]
I removed the package-lock.json from this PR because I'll fix it in another one.

**Comment by Drarig29** [comment]
That's it, I'm done with #39 and #38. You can merge the 3 and publish if you want :wink:

**Pull request merged**
